#image: /home/gavin/ROS_files/maps/1_demo_map.pgm
image: /home/gavin/ROS_files/maps/gmapping_indoor_map.pgm
resolution: 0.050000
origin: [-10.000000, -10.000000, 0.000000]
negate: 0 #0代表 白色为空闲 黑色为占据
occupied_thresh: 0.65 #当占据的概率大于0.65认为被占据
free_thresh: 0.196 #当占据的概率小于0.196认为无障碍物

