# Map size / start point
map_resolution: 0.05
map_size: 2048
map_start_x: 0.5
map_start_y: 0.5 
map_multi_res_levels: 2

#Map update parameterss
map_update_distance_thresh: 0.1
map_update_angle_thresh: 0.04
map_pub_period: 2

update_factor_free:  0.4
update_factor_occupied: 0.9 

laser_min_dist: 0.12
laser_max_dist: 3.5
laser_z_min_dist: -0.1
laser_z_max_dist: 0.1

#tf use
pub_map_odom_transform: true
pub_map_scanmatch_transform: true
use_tf_scan_transformation: true
use_tf_pose_start_estimate: false
tf_map_scanmatch_transform_frame_name: "scanmatcher_frame"


#debug parameters
output_timing:  false
pub_drawings: true
pub_debug_output: true

#advertising config
scan_subscriber_queue_size: 5
scan_topic: "scan"
advertise_map_service: true



